defaults:
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.95
  decay_steps: 4000

arch:
  fully_connected:
  in_features: 3
  hidden_layers: [10, 32, 10, 3]
  activations: [ReLU, ReLU, null, null]

training:
  rec_validation_freq: 1000
  rec_inference_freq: 2000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps: 10000

batch_size:
  boundary: 1000
  initial: 1000
  p_dot: 1000
  q_dot: 1000

custom:
  geometry:
    nr_points: 1000
  dimensions: 2
  masses: [1, 1, 1]
  q0:
    - [0, 0]
  p0:
    - [0,0]
