name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12']
        include:
          - python-version: '3.9'
            commit: false
          - python-version: '3.12'
            commit: false
          - python-version: '3.11'
            commit: false
          - python-version: '3.10'
            commit: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build library
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 setup.py install

      - name: Run tests
        run: |
          pytest tests/
